include ../Common.mak

# prog = $(pdftex2) -fmt pdfetex

test:
	$(pdftex2) -ini ./f.tex
	$(pdftex2) -ini ./f2.tex
	$(pdftex2) -ini ./f3.tex
	$(pdftex2) -ini ./f4.tex

# fmt:
	# $(pdftex2) -ini '*pdfetex.ini'

clean:
	$(clean)

