.TH NEWER 1 "4 January 1998" "Web2C @VERSION@"
.\"=====================================================================
.SH NAME
newer \- compare file modification times
.SH SYNOPSIS
.B newer
.RI [ option ]
.I file1 file2
.\"=====================================================================
.SH DESCRIPTION
Exit successfully if
.I file1
exists and is not older than
.IR file2 .
Also exit successfully if
.I file2
doesn't exist.
.\"=====================================================================
.SH OPTIONS
.B newer
accepts the following options:
.TP
.B --help
.rb
Print help message and exit.
.TP
.B --version
.rb
Print version information and exit.
